#!/usr/bin/env python3
"""Render a review sheet for the icon set -> favicon-preview.png (not shipped)."""
from __future__ import annotations

import os

from PIL import Image, ImageDraw, ImageFont

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PUBLIC = os.path.join(ROOT, "public")
ASSETS = os.path.join(os.path.dirname(os.path.abspath(__file__)), "assets")

W, H = 1240, 862
BG = (247, 247, 249)
INK = (30, 30, 34)
MUTED = (128, 126, 138)


def font(weight: str, size: int) -> ImageFont.FreeTypeFont:
    path = os.path.join(ASSETS, f"Inter-{weight}.ttf")
    if os.path.exists(path):
        return ImageFont.truetype(path, size)
    return ImageFont.truetype("/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf", size)


def load(rel: str) -> Image.Image:
    return Image.open(os.path.join(PUBLIC, rel)).convert("RGBA")


def label(d: ImageDraw.ImageDraw, xy, text, f, fill=MUTED) -> None:
    d.text(xy, text, font=f, fill=fill)


def main() -> None:
    sheet = Image.new("RGB", (W, H), BG)
    d = ImageDraw.Draw(sheet)
    f_h1 = font("600", 30)
    f_h2 = font("600", 17)
    f_body = font("400", 15)
    f_tiny = font("400", 13)
    f_mono = font("600", 14)

    d.text((40, 32), "CreatorTools — icon set", font=f_h1, fill=INK)
    label(d, (40, 72), "Generated by npm run icons · every path and pixel size verified by npm run verify:icons", f_body)

    lx, rx = 40, 660
    colw = 540

    # ---------------------------------------------------------- left: tab ---
    label(d, (lx, 118), "how it reads in a browser tab (real 16 px)", f_h2, INK)
    d.rounded_rectangle([lx, 148, lx + colw, 214], radius=14, fill=(255, 255, 255),
                        outline=(226, 226, 232), width=1)
    d.rounded_rectangle([lx + 1, 148, lx + 168, 214], radius=14, fill=(240, 240, 244))
    tab = load("favicon-16x16.png")
    sheet.paste(tab, (lx + 20, 173), tab)
    d.text((lx + 46, 170), "CreatorTools — Opport…", font=f_tiny, fill=(38, 38, 43))

    # --------------------------------------------------- left: true sizes ---
    label(d, (lx, 250), "true pixel size", f_h2, INK)
    row = [("16", "favicon-16x16.png"), ("32", "favicon-32x32.png"),
           ("180", "apple-touch-icon.png"), ("192", "icons/icon-192.png")]
    x, y = lx, 282
    for name, rel in row:
        im = load(rel)
        sheet.paste(im, (x, y), im)
        d.text((x, y + 196), f"{name}px", font=f_mono, fill=(96, 94, 106))
        x += im.width + 30

    # --------------------------------------------------- left: maskable -----
    label(d, (lx, 512), "maskable (Android adaptive) — mark inside the 80% safe zone", f_h2, INK)
    mask = load("icons/maskable-512.png").convert("RGB").resize((190, 190), Image.LANCZOS)
    sheet.paste(mask, (lx, 544))
    circle = Image.new("L", (190, 190), 0)
    ImageDraw.Draw(circle).ellipse([19, 19, 171, 171], fill=255)
    clipped = Image.new("RGB", (190, 190), BG)
    clipped.paste(mask, (0, 0), circle)
    sheet.paste(clipped, (lx + 230, 544))
    label(d, (lx, 742), "full 512 px asset", f_tiny)
    label(d, (lx + 230, 742), "worst-case circular crop", f_tiny)

    # ------------------------------------------------------- right: dark ---
    label(d, (rx, 118), "on dark surfaces", f_h2, INK)
    strip = Image.new("RGB", (colw, 190), (23, 23, 26))
    sd = ImageDraw.Draw(strip)
    tiles = [("96", "icons/icon-192.png", 96), ("64", "icons/icon-512.png", 64),
             ("16", "favicon-16x16.png", 16)]
    tx = 34
    for name, rel, size in tiles:
        im = load(rel)
        if im.width != size:
            im = im.resize((size, size), Image.LANCZOS)
        strip.paste(im, (tx, 60), im)
        sd.text((tx, 150), f"{name}px", font=f_mono, fill=(140, 138, 152))
        tx += 150
    sheet.paste(strip, (rx, 148))

    # --------------------------------------------------------- right: og ---
    label(d, (rx, 366), "link preview / og-image.png (1200×630)", f_h2, INK)
    og = load("og-image.png").convert("RGB")
    og = og.resize((colw, round(colw * og.height / og.width)), Image.LANCZOS)
    sheet.paste(og, (rx, 398))

    # ------------------------------------------------------- right: notes ---
    notes = [
        "favicon.ico carries 16 / 32 / 48 frames for legacy tabs, bookmarks",
        "and Windows shortcuts.",
        "",
        "favicon.svg takes over on retina displays and in pinned or bookmark",
        "surfaces that accept vector icons.",
        "",
        "Sizes 16 and 32 use a re-proportioned mark — circles pushed further",
        "apart and sampled at 16× — because the tile version blurs into a",
        "single blob below ~24 px.",
    ]
    ny = 706
    for line in notes:
        if line:
            label(d, (rx, ny), line, f_tiny, (96, 94, 106))
        ny += 16

    sheet.save(os.path.join(ROOT, "favicon-preview.png"), optimize=True)
    print("favicon-preview.png written")


if __name__ == "__main__":
    main()
